import fs from 'node:fs';
import path from 'node:path';

export const BACKUP_SUFFIX = '_backup';

/**
 * Check if the file at binPath is already a wrapper script.
 * Detects by checking the first line for the marker comment.
 */
export function isWrapped(binPath) {
  try {
    const fd = fs.openSync(binPath, 'r');
    const buffer = Buffer.alloc(200);
    const bytesRead = fs.readSync(fd, buffer, 0, 200, 0);
    fs.closeSync(fd);
    const firstLine = buffer.toString('utf-8', 0, bytesRead).split('\n')[0];
    return firstLine === '# Auto-generated by @lionad/bin-timeout-wrapper';
  } catch {
    return false;
  }
}

/**
 * Resolve a binary path to an absolute path and validate it.
 * Throws descriptive errors for each failure case.
 */
export function resolveBinPath(binPath) {
  const resolved = path.resolve(binPath);

  if (!fs.existsSync(resolved)) {
    throw new Error(`Binary not found: ${resolved}`);
  }

  const stat = fs.statSync(resolved);
  if (stat.isDirectory()) {
    throw new Error(`Path is a directory, not a file: ${resolved}`);
  }

  // Check if executable (owner, group, or other)
  const mode = stat.mode;
  const isExecutable = (mode & 0o111) !== 0;
  if (!isExecutable) {
    throw new Error(`Binary is not executable: ${resolved}`);
  }

  return resolved;
}

/**
 * Parse a timeout value string to integer.
 * Must be a positive integer.
 */
export function parseTimeout(value) {
  const parsed = Number(value);

  if (!Number.isFinite(parsed) || parsed <= 0 || !Number.isInteger(parsed)) {
    throw new Error(`Invalid timeout: ${value}. Must be a positive integer.`);
  }

  return parsed;
}
