import fs from 'node:fs';
import { isWrapped, resolveBinPath, BACKUP_SUFFIX } from './utils.js';

const WRAPPER_TEMPLATE = `#!/bin/sh
# Auto-generated by @lionad/bin-timeout-wrapper
# Wraps: {bin_path}_backup
# Timeout: {timeout}s (override with BIN_TIMEOUT env var)

TIMEOUT="\${BIN_TIMEOUT:-{timeout}}"
exec perl -e '
  $SIG{ALRM} = sub { kill 9, $$ };
  alarm $ARGV[0];
  exec @ARGV[1..$#ARGV];
' "$TIMEOUT" "{bin_path}_backup" "$@"
`;

export async function wrap(binPath, timeout) {
  const resolvedPath = resolveBinPath(binPath);

  if (isWrapped(resolvedPath)) {
    throw new Error(`Already wrapped: ${resolvedPath}`);
  }

  const backupPath = resolvedPath + BACKUP_SUFFIX;

  if (fs.existsSync(backupPath)) {
    throw new Error(`Backup already exists: ${backupPath}. Remove it or restore first.`);
  }

  fs.renameSync(resolvedPath, backupPath);

  const wrapperContent = WRAPPER_TEMPLATE
    .replaceAll('{bin_path}', resolvedPath)
    .replaceAll('{timeout}', String(timeout));

  fs.writeFileSync(resolvedPath, wrapperContent, 'utf-8');
  fs.chmodSync(resolvedPath, 0o755);

  return { binPath: resolvedPath, backupPath, timeout };
}
