import fs from 'node:fs';
import path from 'node:path';
import { isWrapped, resolveBinPath, BACKUP_SUFFIX } from './utils.js';

/**
 * Escape a string for use inside shell single quotes.
 * Handles ' by ending the quote, adding escaped quote, starting new quote.
 */
function shellSingleQuote(str) {
  return "'" + str.replace(/'/g, "'\\''") + "'";
}

const WRAPPER_TEMPLATE = `#!/bin/sh
# Auto-generated by @lionad/bin-timeout-wrapper
# Wraps: __BIN_PATH___backup
# Timeout: __TIMEOUT__s (override with BIN_TIMEOUT env var)
# Log: __ENABLE_LOG__

TIMEOUT="\${BIN_TIMEOUT:-__TIMEOUT__}"
__LOG_CODE__
exec perl -e '
  use strict;
  use warnings;
  use POSIX qw(setpgid);
  use Time::HiRes qw(time);
  my $timeout = $ARGV[0];
  my $logFile = $ARGV[1];
  die "Invalid BIN_TIMEOUT: $timeout\\n" unless $timeout =~ /^\\d+$/;
  my @cmd = @ARGV[2..$#ARGV];
  defined(my $pid = fork()) or die "fork: $!\\n";
  if ($pid == 0) {
    setpgid(0, 0);
    exec { $cmd[0] } @cmd;
    die "exec: $!\\n";
  }
  $SIG{ALRM} = sub {
    if ($logFile) {
      my $ts = int(time * 1000);
      open(my $fh, ">>", $logFile) or warn "Cannot open log: $!";
      print $fh "[$ts] timeout\\n" if $fh;
      close($fh) if $fh;
    }
    kill 9, -$pid;
    exit(137);
  };
  $SIG{TERM} = sub { kill 15, -$pid; exit(143); };
  $SIG{INT}  = sub { kill 2,  -$pid; exit(130); };
  alarm $timeout;
  waitpid($pid, 0);
  exit($? >> 8 == 0 ? ($? & 127) ? 128 + ($? & 127) : 0 : $? >> 8);
' -- "$TIMEOUT" __LOG_FILE__ __BACKUP_SHELL__ "$@"
`;

export async function wrap(binPath, timeout, enableLog = false) {
  const resolvedPath = resolveBinPath(binPath);

  if (isWrapped(resolvedPath)) {
    throw new Error(`Already wrapped: ${resolvedPath}`);
  }

  const backupPath = resolvedPath + BACKUP_SUFFIX;

  if (fs.existsSync(backupPath)) {
    throw new Error(`Backup already exists: ${backupPath}. Remove it or restore first.`);
  }

  const shellSafeBackup = shellSingleQuote(backupPath);
  const logFilePath = path.join(path.dirname(backupPath), '.bin-timeout-wrapper.log');
  const shellSafeLogFile = enableLog ? shellSingleQuote(logFilePath) : "''";

  // 生成日志代码（如果启用）- 使用 perl 获取毫秒时间戳（跨平台兼容）
  const logCode = enableLog
    ? `perl -e 'use Time::HiRes qw(time); print "[" . int(time * 1000) . "] executed\\n"' >> ${shellSafeLogFile}\n`
    : '';

  const wrapperContent = WRAPPER_TEMPLATE
    .replaceAll('__BIN_PATH__', resolvedPath)
    .replaceAll('__TIMEOUT__', String(timeout))
    .replaceAll('__BACKUP_SHELL__', shellSafeBackup)
    .replaceAll('__ENABLE_LOG__', enableLog ? 'enabled' : 'disabled')
    .replaceAll('__LOG_CODE__', logCode)
    .replaceAll('__LOG_FILE__', shellSafeLogFile);

  // Write to temp file first, then atomic rename to minimize crash window
  const tmpPath = resolvedPath + '.tmp.' + process.pid;
  fs.writeFileSync(tmpPath, wrapperContent, 'utf-8');
  fs.chmodSync(tmpPath, 0o755);
  fs.renameSync(resolvedPath, backupPath);
  fs.renameSync(tmpPath, resolvedPath);

  return { binPath: resolvedPath, backupPath, timeout, enableLog };
}
