import fs from 'node:fs';
import { isWrapped, resolveBinPath, BACKUP_SUFFIX } from './utils.js';

/**
 * Escape a string for use inside shell single quotes.
 * Handles ' by ending the quote, adding escaped quote, starting new quote.
 */
function shellSingleQuote(str) {
  return "'" + str.replace(/'/g, "'\\''") + "'";
}

const WRAPPER_TEMPLATE = `#!/bin/sh
# Auto-generated by @lionad/bin-timeout-wrapper
# Wraps: __BIN_PATH___backup
# Timeout: __TIMEOUT__s (override with BIN_TIMEOUT env var)

TIMEOUT="\${BIN_TIMEOUT:-__TIMEOUT__}"
exec perl -e '
  use strict;
  use warnings;
  use POSIX qw(setpgid);
  my $timeout = $ARGV[0];
  die "Invalid BIN_TIMEOUT: $timeout\\n" unless $timeout =~ /^\\d+$/;
  my @cmd = @ARGV[1..$#ARGV];
  defined(my $pid = fork()) or die "fork: $!\\n";
  if ($pid == 0) {
    setpgid(0, 0);
    exec { $cmd[0] } @cmd;
    die "exec: $!\\n";
  }
  $SIG{ALRM} = sub { kill 9, -$pid; exit(137); };
  $SIG{TERM} = sub { kill 15, -$pid; exit(143); };
  $SIG{INT}  = sub { kill 2,  -$pid; exit(130); };
  alarm $timeout;
  waitpid($pid, 0);
  exit($? >> 8 == 0 ? ($? & 127) ? 128 + ($? & 127) : 0 : $? >> 8);
' -- "$TIMEOUT" __BACKUP_SHELL__ "$@"
`;

export async function wrap(binPath, timeout) {
  const resolvedPath = resolveBinPath(binPath);

  if (isWrapped(resolvedPath)) {
    throw new Error(`Already wrapped: ${resolvedPath}`);
  }

  const backupPath = resolvedPath + BACKUP_SUFFIX;

  if (fs.existsSync(backupPath)) {
    throw new Error(`Backup already exists: ${backupPath}. Remove it or restore first.`);
  }

  const shellSafeBackup = shellSingleQuote(backupPath);

  const wrapperContent = WRAPPER_TEMPLATE
    .replaceAll('__BIN_PATH__', resolvedPath)
    .replaceAll('__TIMEOUT__', String(timeout))
    .replaceAll('__BACKUP_SHELL__', shellSafeBackup);

  // Write to temp file first, then atomic rename to minimize crash window
  const tmpPath = resolvedPath + '.tmp.' + process.pid;
  fs.writeFileSync(tmpPath, wrapperContent, 'utf-8');
  fs.chmodSync(tmpPath, 0o755);
  fs.renameSync(resolvedPath, backupPath);
  fs.renameSync(tmpPath, resolvedPath);

  return { binPath: resolvedPath, backupPath, timeout };
}
